"""Verification Skill 硬门禁公共 API。"""

from .engine import VerificationEngine
from .gates import aggregate_verdict
from .models import (
    ARTICLE_LINT_WARNING_PATTERNS,
    ARTICLE_MAX_INPUT_TOKENS,
    ARTICLE_MAX_VERIFICATION_ATTEMPTS,
    BehaviorEvidence,
    BehaviorGateSpec,
    BehaviorObservation,
    BehaviorScenarioSpec,
    CommandEvidence,
    CommandSpec,
    FrozenVerificationSkill,
    GateKind,
    GateResult,
    GateStatus,
    LintGateSpec,
    LogEvidence,
    LogGateSpec,
    LogObservation,
    ScenarioCollection,
    ScenarioSpec,
    TraceEvidence,
    TraceGateSpec,
    TraceObservation,
    ToolCallObservation,
    UIGateSpec,
    UnitGateSpec,
    Variant,
    VerificationPolicy,
    VerificationReport,
    VerificationRunRequest,
    VerificationSkillSpec,
    VerificationVerdict,
    command_contract_digest,
)
from .providers import (
    BehaviorEvidenceProvider,
    EvidenceCollectionContext,
    LogEvidenceProvider,
    TraceEvidenceProvider,
)
from .runner import CommandRunner, workspace_digest
from .skill import VerificationSkillError, VerificationSkillLoader
from .store import (
    AttestedJsonEvidenceStore,
    JsonEvidenceStore,
    VerificationAttestation,
    VerificationEvidenceStore,
)

__all__ = [
    "ARTICLE_LINT_WARNING_PATTERNS",
    "ARTICLE_MAX_INPUT_TOKENS",
    "ARTICLE_MAX_VERIFICATION_ATTEMPTS",
    "AttestedJsonEvidenceStore",
    "BehaviorEvidence",
    "BehaviorEvidenceProvider",
    "BehaviorGateSpec",
    "BehaviorObservation",
    "BehaviorScenarioSpec",
    "CommandEvidence",
    "CommandRunner",
    "CommandSpec",
    "FrozenVerificationSkill",
    "EvidenceCollectionContext",
    "GateKind",
    "GateResult",
    "GateStatus",
    "JsonEvidenceStore",
    "LintGateSpec",
    "LogEvidence",
    "LogEvidenceProvider",
    "LogGateSpec",
    "LogObservation",
    "ScenarioCollection",
    "ScenarioSpec",
    "TraceEvidence",
    "TraceEvidenceProvider",
    "TraceGateSpec",
    "TraceObservation",
    "ToolCallObservation",
    "UIGateSpec",
    "UnitGateSpec",
    "Variant",
    "VerificationEngine",
    "VerificationEvidenceStore",
    "VerificationPolicy",
    "VerificationReport",
    "VerificationRunRequest",
    "VerificationSkillError",
    "VerificationSkillLoader",
    "VerificationSkillSpec",
    "VerificationAttestation",
    "VerificationVerdict",
    "aggregate_verdict",
    "command_contract_digest",
    "workspace_digest",
]
